version: "3.8"

services:
  apt-cacher-ng:
    build:
      context: ./apt-cacher-ng
      dockerfile: Dockerfile
    volumes:
      - apt-cache:/var/cache/apt-cacher-ng
    ports:
      - "3142:3142"
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "1.0"
    #       memory: 512M

  squid-deb-proxy:
    build:
      context: ./squid-deb-proxy # Path to the new Dockerfile
      dockerfile: Dockerfile
    volumes:
      - squid-cache:/var/spool/squid-deb-proxy
    ports:
      - "3142:3142"

  verdaccio:
    image: verdaccio/verdaccio
    volumes:
      # - ./verdaccio/config.yaml:/verdaccio/conf/config.yaml
      - verdaccio_storage:/verdaccio/storage
    ports:
      - "4873:4873"

  runner:
    image: pwd9000-github-runner-lin:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ryan/.local/share/pnpm/store/v3:/home/docker/.pnpm-store
      # - /run/media/ryan/ubuntu/cache:/home/docker/cache
    build:
      network: host
      context: .
      dockerfile: Dockerfile
      args:
        RUNNER_VERSION: "2.314.1"
        DOCKER_GID: ${DOCKER_GID}
    environment:
      GH_TOKEN: ${GH_TOKEN}
      GH_OWNER: ${GH_OWNER}
      GH_REPOSITORY: ${GH_REPOSITORY}
    depends_on:
      - apt-cacher-ng
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "1.0"
    #       memory: 2048M

  runner2:
    image: pwd9000-github-runner-lin:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ryan/.local/share/pnpm/store/v3:/home/docker/.pnpm-store
      - /run/media/ryan/ubuntu/cache:/home/docker/cache
    build:
      network: host
      context: .
      dockerfile: Dockerfile
      args:
        RUNNER_VERSION: "2.314.1"
        DOCKER_GID: ${DOCKER_GID}
    environment:
      GH_TOKEN: ${GH_TOKEN2}
      GH_OWNER: ${GH_OWNER2}
      GH_REPOSITORY: ${GH_REPOSITORY2}
    depends_on:
      - apt-cacher-ng
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "1.0"
    #       memory: 2048M

  runner3:
    image: pwd9000-github-runner-lin:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ryan/.local/share/pnpm/store/v3:/home/docker/.pnpm-store
      - /run/media/ryan/ubuntu/cache:/home/docker/cache
    build:
      network: host
      context: .
      dockerfile: Dockerfile
      args:
        RUNNER_VERSION: "2.314.1"
        DOCKER_GID: ${DOCKER_GID}
    environment:
      GH_TOKEN: ${GH_TOKEN3}
      GH_OWNER: ${GH_OWNER3}
      GH_REPOSITORY: ${GH_REPOSITORY3}
    depends_on:
      - apt-cacher-ng
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "1.0"
    #       memory: 2048M

  runner4:
    image: pwd9000-github-runner-lin:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ryan/.local/share/pnpm/store/v3:/home/docker/.pnpm-store
      - /run/media/ryan/ubuntu/cache:/home/docker/cache
    build:
      network: host
      context: .
      dockerfile: Dockerfile
      args:
        RUNNER_VERSION: "2.314.1"
        DOCKER_GID: ${DOCKER_GID}
    environment:
      GH_TOKEN: ${GH_TOKEN4}
      GH_OWNER: ${GH_OWNER4}
      GH_REPOSITORY: ${GH_REPOSITORY4}
    depends_on:
      - apt-cacher-ng
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "1.0"
    #       memory: 2048M

volumes:
  apt-cache: {}
  squid-cache: {}
  verdaccio_storage: {}
